# Generated by Django 5.2.7 on 2025-10-23 16:56

import django.core.validators
import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=django.core.validators.MaxLengthValidator(100, message='Name must be at most 100 characters long'))),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='Age must be at least 18'), django.core.validators.MaxValueValidator(60, message='Age must be at most 60')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(validators=[employee.models.validate_department])),
                ('image', models.ImageField(null=True, upload_to='student_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
