# Generated by Django 5.2.7 on 2025-10-24 05:43

import django.core.validators
import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Name is required.'}, validators=[django.core.validators.MaxLengthValidator(100, message='Name must be at most 100 characters long')])),
                ('email', models.EmailField(error_messages={'required': 'Email is required.'}, max_length=254, unique=True)),
                ('salary', models.IntegerField(error_messages={'required': 'Salary is required.'}, validators=[django.core.validators.MinValueValidator(0, message='Salary must be greater than 0'), django.core.validators.MaxValueValidator(1000000, message='Salary must be less than Rs. 1000000')])),
                ('phone', models.CharField(error_messages={'max_length': 'Phone number must be at most 10 characters long.', 'required': 'Phone number is required.'}, max_length=10)),
                ('designation', models.CharField(error_messages={'required': 'Designation is required.'}, validators=[employee.models.validate_designation])),
                ('department', models.CharField(error_messages={'required': 'Department is required.'}, validators=[employee.models.validate_department])),
                ('date_of_joining', models.DateField(error_messages={'required': 'Date of joining is required.'})),
                ('status', models.BooleanField(default=True, validators=[employee.models.validate_status])),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
