# Generated by Django 5.2.7 on 2025-10-24 05:51

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(error_messages={'max_length': 'Phone number must be at most 10 characters long.', 'required': 'Phone number is required.'}, validators=[employee.models.validate_phone]),
        ),
    ]
