# Generated by Django 5.2.7 on 2025-10-24 10:39

import django.core.validators
import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'Name must be at most 100 characters long.', 'required': 'Name is required.'}, max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters long')])),
                ('email', models.EmailField(error_messages={'required': 'Email is required.', 'unique': 'Email must be unique.'}, max_length=254, unique=True)),
                ('password', models.CharField(error_messages={'min_length': 'Password must be at least 8 characters long.', 'required': 'Password is required.'}, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long')])),
                ('role', models.CharField(validators=[employee.models.validate_role])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(error_messages={'required': 'Name is required.'}, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters long'), django.core.validators.MaxLengthValidator(100, message='Name must be at most 100 characters long')]),
        ),
    ]
