# Generated by Django 5.2.7 on 2025-10-24 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_user_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(error_messages={'required': 'Password is required.'}, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long')]),
        ),
    ]
